[project]
name = "wyoming-api"
version = "0.2.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "httpx>=0.28.1",
    "wyoming>=1.8.0",
]

[project.scripts]
wwac = "wwac.__main__:main"