name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-helm-chart:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      CHART_NAME: whisper-wyoming-openvino

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.19.0'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm chart
        run: |
          helm package helm/${{ env.CHART_NAME }}

      - name: Push Helm chart to GHCR
        run: |
          CHART_VERSION=$(helm show chart helm/${{ env.CHART_NAME }} | awk '/^version:/ {print $2}')
          helm push ${{ env.CHART_NAME }}-${CHART_VERSION}.tgz oci://${{ env.REGISTRY }}/${{ github.repository_owner }}

      - name: Output chart details
        run: |
          CHART_VERSION=$(helm show chart helm/${{ env.CHART_NAME }} | awk '/^version:/ {print $2}')
          echo "Chart pushed successfully!"
          echo "Chart: ${{ env.CHART_NAME }}"
          echo "Version: ${CHART_VERSION}"
          echo "Registry: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.CHART_NAME }}"
          echo ""
          echo "To install this chart:"
          echo "  helm install my-release oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.CHART_NAME }} --version ${CHART_VERSION}"
